### PR TITLE
Add `tlCursedVersions` setting

### PR DESCRIPTION
**Pull request by armanbilge**
For excluding mucked up or otherwise unpublished versions from mima checks. We've all been there. (Name subject to bikeshed.)

### CODE REVIEW

**Comment by rossabaker** [comment]
I usually just run my own filterNot on these, which can additionally target specific Scala versions.  I don't have an objection to it, but I don't know that the setting adds much here.

**Comment by armanbilge** [comment]
That's a good point. I think the `filterNot` on `mimaPreviousArtifacts` is slightly more tedious because it's a set of module IDs and not versions. In any case I'm happy to let this sit and see if anyone really wants it.

**Comment by armanbilge** [comment]
Maybe the setting we are actually missing is a `tlPreviousVersions`, that is auto-populated by our plugin and then can be introspected/modified by the user.

**Comment by rossabaker** [comment]
In that world, is tlVersionIntroduced still useful?  I guess it helps people avoid filtering on an ordering of whatever semver representation is settled on.

**Comment by armanbilge** [comment]
I've migrated a lot of builds and this hasn't come up. Happy to revisit if someone wants it.

**Pull request closed without merging**
