### PR TITLE
Use Jitpack.io to host snapshot Scaladoc

### LINKED ISSUE #226: `apiURL` should be set for snapshot builds
Making a note of this so I don't forget!

Scaladoc inter-module linking does not seem to work unless the modules that you wish to link to have set `apiURL`. This causes this URL to be passed as a piece of external mapping configuration when Scaladoc is invoked. When this is missing, Scaladoc produces a warning as it cannot find any definition to link to.

At the moment `apiURL` is not set for snapshots or sbt plugins, because we link to [javadoc.io](https://javadoc.io) which does not support either. This means that snapshot builds for projects with inter-module Scaladoc links will fail in CI as fatal warnings is enabled by default.

For local builds (`githubIsWorkFlowBuild` is false) we could use `(crossTarget.value / "api").toURI.toURL`, as this is the output directory for Scaladoc.

It's possible we could use JAR URLs for snapshot builds, i.e.
```scala
val modName = moduleName.value
val host = sonatypeCredentialHost.value
val org = organization.value.replace(".", "/")
val mod = cross(modName)
val ver = version.value
val art = s"${modName}-${ver}-javadoc.jar"
url(s"jar:https://${host}/content/repositories/snapshots/${org}/${mod}/${ver}/${art}!/")
```
===>
```
jar:https://oss.sonatype.org/content/repositories/snapshots/org/typelevel/sbt-typelevel-docs_2.12/0.4.6-16-bc913e6-20220325T001241Z-SNAPSHOT/sbt-typelevel-docs-0.4.6-16-bc913e6-20220325T001241Z-SNAPSHOT-javadoc.jar!/
```

### PR DESCRIPTION
**Pull request by DavidGregory084**
Resolves #226 as suggested on the ticket discussion.

Can you foresee any problems arising from making the sonatype plugin depend on the github plugin?

This seems to work fine within sbt-typelevel itself as far as I can tell. I think that the usage of `TypelevelUnidocsPlugin` points every submodule to the unidoc artifact as it sets `ThisBuild \ apiURL`:

```
sbt:sbt-typelevel> show apiURL
[info] noPublish / apiURL
[info] 	Some(https://javadoc.jitpack.io/com/github/typelevel/sbt-typelevel/sbt-typelevel-docs_2.12/344a315c517b39d93e85d3eb3b0131c2261b00fe/)
[info] ci / apiURL
[info] 	Some(https://javadoc.jitpack.io/com/github/typelevel/sbt-typelevel/sbt-typelevel-docs_2.12/344a315c517b39d93e85d3eb3b0131c2261b00fe/)
[info] core / apiURL
[info] 	Some(https://javadoc.jitpack.io/com/github/typelevel/sbt-typelevel/sbt-typelevel-docs_2.12/344a315c517b39d93e85d3eb3b0131c2261b00fe/)
[info] site / apiURL
[info] 	Some(https://javadoc.jitpack.io/com/github/typelevel/sbt-typelevel/sbt-typelevel-docs_2.12/344a315c517b39d93e85d3eb3b0131c2261b00fe/)
[info] github / apiURL
[info] 	Some(https://javadoc.jitpack.io/com/github/typelevel/sbt-typelevel/sbt-typelevel-docs_2.12/344a315c517b39d93e85d3eb3b0131c2261b00fe/)
[info] versioning / apiURL
[info] 	Some(https://javadoc.jitpack.io/com/github/typelevel/sbt-typelevel/sbt-typelevel-docs_2.12/344a315c517b39d93e85d3eb3b0131c2261b00fe/)
[info] ciSigning / apiURL
[info] 	Some(https://javadoc.jitpack.io/com/github/typelevel/sbt-typelevel/sbt-typelevel-docs_2.12/344a315c517b39d93e85d3eb3b0131c2261b00fe/)
[info] mima / apiURL
[info] 	Some(https://javadoc.jitpack.io/com/github/typelevel/sbt-typelevel/sbt-typelevel-docs_2.12/344a315c517b39d93e85d3eb3b0131c2261b00fe/)
[info] ciRelease / apiURL
[info] 	Some(https://javadoc.jitpack.io/com/github/typelevel/sbt-typelevel/sbt-typelevel-docs_2.12/344a315c517b39d93e85d3eb3b0131c2261b00fe/)
[info] settings / apiURL
[info] 	Some(https://javadoc.jitpack.io/com/github/typelevel/sbt-typelevel/sbt-typelevel-docs_2.12/344a315c517b39d93e85d3eb3b0131c2261b00fe/)
[info] docs / apiURL
[info] 	Some(https://javadoc.jitpack.io/com/github/typelevel/sbt-typelevel/sbt-typelevel-docs_2.12/344a315c517b39d93e85d3eb3b0131c2261b00fe/)
[info] githubActions / apiURL
[info] 	Some(https://javadoc.jitpack.io/com/github/typelevel/sbt-typelevel/sbt-typelevel-docs_2.12/344a315c517b39d93e85d3eb3b0131c2261b00fe/)
[info] mergify / apiURL
[info] 	Some(https://javadoc.jitpack.io/com/github/typelevel/sbt-typelevel/sbt-typelevel-docs_2.12/344a315c517b39d93e85d3eb3b0131c2261b00fe/)
[info] unidoc / apiURL
[info] 	Some(https://javadoc.jitpack.io/com/github/typelevel/sbt-typelevel/sbt-typelevel-docs_2.12/344a315c517b39d93e85d3eb3b0131c2261b00fe/)
[info] sonatypeCiRelease / apiURL
[info] 	Some(https://javadoc.jitpack.io/com/github/typelevel/sbt-typelevel/sbt-typelevel-docs_2.12/344a315c517b39d93e85d3eb3b0131c2261b00fe/)
[info] sonatype / apiURL
[info] 	Some(https://javadoc.jitpack.io/com/github/typelevel/sbt-typelevel/sbt-typelevel-docs_2.12/344a315c517b39d93e85d3eb3b0131c2261b00fe/)
[info] kernel / apiURL
[info] 	Some(https://javadoc.jitpack.io/com/github/typelevel/sbt-typelevel/sbt-typelevel-docs_2.12/344a315c517b39d93e85d3eb3b0131c2261b00fe/)
[info] apiURL
[info] 	Some(https://javadoc.jitpack.io/com/github/typelevel/sbt-typelevel/sbt-typelevel-docs_2.12/344a315c517b39d93e85d3eb3b0131c2261b00fe/)
```

### CODE REVIEW

**Comment by DavidGregory084** [comment]
Hmm, might be good to take a pause on this one actually

**Comment by DavidGregory084** [comment]
See e.g. https://javadoc.jitpack.io/com/github/cb372/scalacache/scalacache-unidoc_2.13/bdff1e9a0c13fb6cde8968fa6aafd00d9ffeabfa/

The problem is that the commit hash is not in the fork, not the base repo

**Comment by DavidGregory084** [comment]
Hmm, no luck on e.g. https://javadoc.jitpack.io/com/github/opencastsoftware/sbt-typelevel/sbt-typelevel-docs_2.12/344a315c517b39d93e85d3eb3b0131c2261b00fe/javadoc/org/typelevel/sbt/TypelevelGitHubPlugin$.html.

**Comment by armanbilge** [comment]
Yeah, jitpack.io is very cool but unconfigured can be brittle. For example I think it uses JDK 8 by default, which means any repository that requires a newer JDK won't work. For example, my original experiment with fs2 succeeded for `fs2-core` but not for `fs2-io`, nor the unidocs artifact since the build crashes once it hits `fs2-io`.

**Comment by DavidGregory084** [comment]
The [build log](https://jitpack.io/com/github/opencastsoftware/sbt-typelevel/344a315c51/build.log) actually looks OK, although it looks like sbt-git may be struggling to list tags.

**Comment by armanbilge** [comment]
What's up with the file list at the end though?
```
Files: 
com/github/opencastsoftware/sbt-typelevel/344a315c51
com/github/opencastsoftware/sbt-typelevel/344a315c51/build.log
com/github/opencastsoftware/sbt-typelevel/344a315c51/sbt-typelevel-344a315c51-javadoc.jar
com/github/opencastsoftware/sbt-typelevel/344a315c51/sbt-typelevel-344a315c51-javadoc.jar.md5
com/github/opencastsoftware/sbt-typelevel/344a315c51/sbt-typelevel-344a315c51-javadoc.jar.sha1
com/github/opencastsoftware/sbt-typelevel/344a315c51/sbt-typelevel-344a315c51-sources.jar
com/github/opencastsoftware/sbt-typelevel/344a315c51/sbt-typelevel-344a315c51-sources.jar.md5
com/github/opencastsoftware/sbt-typelevel/344a315c51/sbt-typelevel-344a315c51-sources.jar.sha1
com/github/opencastsoftware/sbt-typelevel/344a315c51/sbt-typelevel-344a315c51.jar
com/github/opencastsoftware/sbt-typelevel/344a315c51/sbt-typelevel-344a315c51.jar.md5
com/github/opencastsoftware/sbt-typelevel/344a315c51/sbt-typelevel-344a315c51.jar.sha1
com/github/opencastsoftware/sbt-typelevel/344a315c51/sbt-typelevel-344a315c51.pom
com/github/opencastsoftware/sbt-typelevel/344a315c51/sbt-typelevel-344a315c51.pom.md5
com/github/opencastsoftware/sbt-typelevel/344a315c51/sbt-typelevel-344a315c51.pom.sha1
```

**Comment by armanbilge** [comment]
Interesting, they seem to be hosted here:
https://javadoc.jitpack.io/com/github/opencastsoftware/sbt-typelevel/344a315c51/javadoc/

**Comment by DavidGregory084** [comment]
Woah that section of the build log was not even showing up for me! Looks like navigating to basically any links in there doesn't work though unfortunately. 😞

**Comment by armanbilge** [comment]
It's really strange. The links are busted, but direct links seem to work.
https://javadoc.jitpack.io/com/github/opencastsoftware/sbt-typelevel/344a315c51/javadoc/org/typelevel/sbt/TypelevelGitHubPlugin$.html

**Comment by DavidGregory084** [comment]
Yeah, in fact it seems that it's every `index.html` page, which is frustrating because that affects every package root page in a Scaladoc.

**Comment by DavidGregory084** [comment]
I think we need answer on jitpack/jitpack.io#5056 in order to know how to proceed on this one - are the Scaladocs hosted in the root module because we have used unidoc?

If we did not use unidoc would they be missing from the root and present as submodules? That's a tricky thing to resolve in sbt-typelevel because we would need to know somehow whether the `apiURL` was set by `TypelevelUnidocPlugin` or by something else.

**Comment by armanbilge** [comment]
My guess is it's a combination of two things:
1. jitpack.io treats single-module and multi-module projects differently:
    https://docs.jitpack.io/#javadoc-publishing
2. Because sbt plugins aren't published correctly, the unidocs become effectively the only artifact in this repo.
    https://github.com/sbt/sbt/issues/3410

**Comment by DavidGregory084** [comment]
>     2. Because sbt plugins aren't published correctly, the unidocs become effectively the only module in this repo.
>        [The maven pattern for sbt plugins is invalid based on the spec sbt/sbt#3410](https://github.com/sbt/sbt/issues/3410)
> 
> 
> Btw, (2) is the reason that javadoc.io also doesn't support sbt.

Oh yeah, I forgot about that particular can of worms. 😞 Hopefully it will be fixed in sbt 2.x.

**Comment by DavidGregory084** [comment]
That definitely seems to be supported by the fact that the scalacache unidoc module *can* be resolved independently: https://javadoc.jitpack.io/com/github/opencastsoftware/scalacache/scalacache-unidoc_2.13/bdff1e9a0c13fb6cde8968fa6aafd00d9ffeabfa/javadoc/

**Comment by armanbilge** [comment]
In any case, that still means this plugin needs to know whether its the only (published) module in the project to set the URLs appropriately. Unless jitpack.io is able to support the multi-module URL for single-module repos as well.

**Comment by DavidGregory084** [comment]
Yeah, that would be really awkward - I don't think it can be done in an sbt Setting as we would need to extract the project structure.

**Comment by armanbilge** [comment]
@DavidGregory084 do you have any new ideas about this? Enough projects are affected that I'd like to ship a fix, finally, but all the solutions so far seem to have caveats. jitpack.io is cool, but brittle, and the jar URLs are solid but unsupported 😕

**Comment by armanbilge** [comment]
Aha, I thought I checked before but this seems to work!
https://s01.oss.sonatype.org/service/local/repositories/snapshots/archive/co/fs2/fs2-docs_2.13/3.2.7-78-a4c60a9-SNAPSHOT/fs2-docs_2.13-3.2.7-78-a4c60a9-SNAPSHOT-javadoc.jar/!/fs2/index.html

**Comment by armanbilge** [comment]
Brilliant, and here it is for cats :)
https://s01.oss.sonatype.org/service/local/repositories/snapshots/archive/org/typelevel/cats-docs_2.13/2.8-a5ade30-SNAPSHOT/cats-docs_2.13-2.8-a5ade30-SNAPSHOT-javadoc.jar/!/index.html

**Comment by DavidGregory084** [comment]
Oh my gosh, that's awesome! So glad to see an approach that works for this!

**Pull request closed without merging**
