### PR TITLE
update plugin doc

### PR DESCRIPTION
**Pull request by mzuehlke**
* resolve merge conflict
* fix outdated links
* update plugins with their settings, tasks and commands

### CODE REVIEW

**Review by armanbilge — APPROVED** [review]
Thank you so much, and also for catching those merge conflicts I slipped through 😬 very appreciated!!

**Comment by mzuehlke** [comment]
I wanted to update the plugins.{dot, svg}, too.
But wanted wanted to get this one done first.

I also didn't added the `sbt-typelevel-github-actions` plugin, but stayed away from it because of #470

**Comment by armanbilge** [comment]
@mzuehlke would you be interested to become a maintainer on sbt-typelevel? I'd appreciate the help ☺️

**Comment by mzuehlke** [comment]
> @mzuehlke would you be interested to become a maintainer on sbt-typelevel? I'd appreciate the help ☺️

If I can be of any help, I am happy to help 👍

**Pull request merged**
