### PR TITLE
New light theme for `sbt-typelevel-site`!

### PR DESCRIPTION
**Pull request by j-mie6**
Changed the default Helium theme over to one more clearly embodying the typelevel colours as found on the main website. Reworked the colours and syntax highlighting. Colours taken from typelevel are clearly labelled as such.

Here is an example:

image

### CODE REVIEW

**Comment by rossabaker** [comment]
I like it, but I'm concerned about accessibility with the low contrast on the left.  It can be checked against [WCAG guidelines](https://webaim.org/resources/contrastchecker/).  Incidentally, the current version passes for large text and fails for small text, so this is a great chance to improve the status quo, too!

**Comment by j-mie6** [comment]
I did check the syntax colouring for any concerns under firefox accessibility tools, and it was fine, didn't check side bar

**Comment by j-mie6** [comment]
Yup, even `redTl`, (which actually looks a tad nicer imo) is a bit shy of the contrast requirements, I'll see if I can brighten the light pink a little more to fix it and will post an update screenshot :)

**Comment by j-mie6** [comment]
image

@rossabaker hopefully that's a bit better

**Review by rossabaker — APPROVED** [review]
I think maybe I'd rather a code light theme to go with the rest of the light theme, but that's not really the point of this PR anyway.  This is a good idea and it looks like an improvement to me.

**Comment by armanbilge** [comment]
FF4S has a nice light theme we might take inspiration from.
https://buntec.github.io/ff4s/examples/counter.html

**Comment by j-mie6** [comment]
I can definitely make a code light theme, then can use this one for the (future) dark theme; light theme code highlighting is a bit trickier imo (weirdly!), So that can always come in a later PR (this doesn't need to be final, after all!

**Review by armanbilge — APPROVED** [review]
Personally I'm very excited about this. I can't thank you enough! 🥰 

@danicheg @satorg @ChristopherDavenport polite pings in case you have any opinions :)

**Review by danicheg — APPROVED** [review]
I like this 👍🏻 But it'd be good to check that this colour palette is also fine for people with visual impairments https://www.whocanuse.com/.

**Review by mzuehlke — APPROVED** [review]

**Comment by j-mie6** [comment]
> I like this 👍🏻 But it'd be good to check that this colour palette is also fine for people with visual impairments https://www.whocanuse.com/.

I did run it through the Firefox impairment simulators at least and things seemed fine. Except for red-less colour blindness, that was fine but just... Bleak. That's to be expected, of course.

**Comment by j-mie6** [comment]
That said, if any issues come up I'll be happy to find a fix for them :) (just @ me)

**Comment by armanbilge** [comment]
@all-contributors add @j-mie6 for design

**Pull request merged**
