### PR TITLE
add scala 3 release version flag

### PR DESCRIPTION
**Pull request by i10416**

### CODE REVIEW

**Comment by i10416** [comment]
rel https://github.com/typelevel/sbt-typelevel/issues/138

**Comment by armanbilge** [comment]
Thanks for the PR! :) A few quick notes:

- Actually the compiler flag was renamed to `-scala-output-version` :)
- Unfortunately, adding the compiler flag is not sufficient; we also need to modify the POM to use the old Scala standard library instead of thew one. Fortunately, sbt 1.7.0 will implement the extra functionality, so we can directly integrate with their setting.
    https://github.com/sbt/sbt/releases/tag/v1.7.0-M1
- I think we should make the default Scala 3.1.1

Also, would you mind targeting your PR at `main` branch instead of `series/0.4`? We will release this feature in sbt-typelevel v0.5.0 :)

**Comment by i10416** [comment]
Hmm, should we wrap `scalaOutputVersion := "3.0.2"` in `tlScalaRelease` rather than exposing it to users?

**Comment by armanbilge** [comment]
That's a good question. I don't think we need our own `tlScalaRelease` setting. I'm not sure what we would use it for.

**Comment by i10416** [comment]
Sure.

In addition, are we going to use `scalaOutputVersion` here, which is still pre-release , or wait for next sbt release?. What do you think?

**Comment by armanbilge** [comment]
I think it's too hard to support this Scala 3 feature without relying on the sbt integration. So, we definitely need to rely on that feature.

I can't promise I'll merge this PR right away. I have to double-check when the planned release date for sbt v1.7.0 is and and decide whether sbt-typelevel v0.5.0 should wait for it or not. I don't currently feel a big rush to release sbt-typelevel v0.5.0 so that strategy may make sense.

Meanwhile I am publishing some milestone prereleases of sbt-typelevel v0.5.0 so some people can use that with the sbt milestone prerelease, if they want.

**Comment by i10416** [comment]
Okay. I'm not in a hurry too. 
We'd better waiting for sbt 1.7.0 release for v0.5.0. I close this PR for now so that someone desperately needs that feature can feel free to open PR.

**Comment by i10416** [comment]
@armanbilge Thanks for reviewing :)

**Comment by armanbilge** [comment]
Thanks for your contribution! :)

**Comment by armanbilge** [comment]
@i10416 if you're still interested in working on this one, I had an idea for how we can do this so it will be ready before sbt 1.7.0 is released, and also so we don't have to bump to sbt-typelevel 0.5.0.

Basically, the idea is to use sbt "reflection", when you refer to a setting using a `String`. Here's an example:
https://github.com/typelevel/sbt-typelevel/blob/66b313c7bdd7c6a8f35b5d6c41c9c4f9a19a773b/sonatype/src/main/scala/org/typelevel/sbt/TypelevelUnidocPlugin.scala#L38
This technique will work even if somebody uses sbt-typelevel with sbt 1.6.x. It won't _do_ anything, but at least it won't crash the build :)

**Comment by i10416** [comment]
@armanbilge  Interesting! I didn't know that technique.

**Pull request closed without merging**
